version: '3'
services:
  db:
    image: mysql:5.7
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: dbauth
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin123!
    ports:
      - "6033:3306"

  config-server:
    image: config-server
    container_name: config-server
    build:
      context: ./config-server
      dockerfile: Dockerfile
    ports:
    - "9101:9101"
    expose:
      - "9101"
    networks:
      - library-network

  eureka-server:
    depends_on:
      - config-server
    image: eureka-server
    container_name: eureka-server
    build:
      context: ./eureka-server
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    expose:
      - "8761"
    environment:
      WAIT_HOSTS: config-server:9101
    networks:
      - library-network

  auth-server:
    depends_on:
      - config-server
      - eureka-server
      - db
    image: auth-server
    container_name: auth-server
    build:
      context: ./auth-server
      dockerfile: Dockerfile
    ports:
      - "9191:9191"
    expose:
      - "9191"
    environment:
      WAIT_HOSTS : db:3306, eureka-server:8761, config-server:9101
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/dbauth?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin123!
    networks:
      - library-network

networks:
  library-network:



