version: '3'
services:
  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "8080:8080"
    networks:
      - library-network

  db:
    image: bitnami/mysql:8.0.22-debian-10-r6
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: dbauth
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin123!
    ports:
      - "6033:3306"
    volumes:
      - ./livrables/dbauth:/docker-entrypoint-initdb.d
    networks:
      - library-network

config-server:
  image: config-server
  container_name: config-server
  build:
    context: ./config-server
    dockerfile: Dockerfile
  ports:
    - "9101:9101"
  expose:
    - "9101"
  networks:
    - library-network

  eureka-server:
    depends_on:
      - config-server
    image: eureka-server
    container_name: eureka-server
    build:
      context: ./eureka-server
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    expose:
      - "8761"
    environment:
      WAIT_HOSTS: config-server:9101
    networks:
      - library-network

  auth-server:
    depends_on:
      - config-server
      - eureka-server
      - db
    image: auth-server
    container_name: auth-server
    build:
      context: ./auth-server
      dockerfile: Dockerfile
    ports:
      - "9191:9191"
    expose:
      - "9191"
    environment:
      WAIT_HOSTS: config-server:9101, eureka-server:8761, db:3306
    networks:
      - library-network

  library-book:
    depends_on:
      - config-server
      - eureka-server
      - db
      - auth-server
    image: library-book
    container_name: library-book
    build:
      context: ./library-book
      dockerfile: Dockerfile
    ports:
      - "9001:9001"
    expose:
      - "9001"
    environment:
      WAIT_HOSTS: config-server:9101, eureka-server:8761, db:3306
    networks:
      - library-network

  library-loan:
    depends_on:
      - config-server
      - eureka-server
      - db
      - auth-server
    image: library-loan
    container_name: library-loan
    build:
      context: ./library-loan
      dockerfile: Dockerfile
    ports:
      - "9002:9002"
    expose:
      - "9002"
    environment:
      WAIT_HOSTS: config-server:9101, eureka-server:8761, db:3306
    networks:
      - library-network

  zuul-server:
    depends_on:
      - config-server
      - eureka-server
      - auth-server
      - library-book
      - library-loan
    image: zuul-server
    container_name: zuul-server
    build:
      context: ./zuul-server
      dockerfile: Dockerfile
    ports:
      - "9004:9004"
    expose:
      - "9004"
    environment:
      WAIT_HOSTS: config-server:9101, eureka-server:8761
    networks:
      - library-network

  client-ui:
    depends_on:
      - config-server
      - eureka-server
      - auth-server
    image: client-ui
    container_name: client-ui
    build:
      context: ./client-ui
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    expose:
      - "8000"
    environment:
      WAIT_HOSTS: config-server:9101, eureka-server:8761, auth-server:9191
    networks:
      - library-network


networks:
  library-network:

