version: '3'
services:
  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "8080:8080"
    networks:
      - library-network

  db:
    image: bitnami/mysql:8.0.22-debian-10-r6
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: dbauth
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin123!
    ports:
      - "6033:3306"
    volumes:
      - ./livrables/dbauth:/docker-entrypoint-initdb.d
      - db_data:/bitnami/mysql/data
    networks:
      - library-network

  
      
  client-ui:
    image: client-ui
    container_name: client-ui
    build:
      context: ./client-ui
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    expose:
      - "8000"
    environment:
      SPRING_CONFIG_URI: http://config-server:9101
      EUREKA_SERVER_URL: http://eureka-server:8761/eureka/
    networks:
      - library-network

volumes :
  db_data:

networks:
  library-network:

