version: '3'
services:
  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "8080:8080"
    networks:
      - ocpizza-network

  database:
    image: bitnami/mysql:8.0.22-debian-10-r6
    container_name: database
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: db_auth
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin123!
    ports:
      - "6033:3306"
    volumes:
      - ./livrables/dbauth:/docker-entrypoint-initdb.d
      - db_data:/bitnami/mysql/data
    networks:
      - ocpizza-network

  config-server:
    image: config-server
    container_name: config-server
    build:
      context: ./config-server
      dockerfile: Dockerfile
    ports:
      - "9101:9101"
    expose:
      - "9101"
    environment:
      SPRING_CONFIG_SERVER_URI: https://github.com/vancharlotte/config-server-repository.git
    networks:
      - ocpizza-network

  eureka-server:
    depends_on:
      - config-server
    image: eureka-server
    container_name: eureka-server
    build:
      context: ./eureka-server
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    expose:
      - "8761"
    environment:
      SPRING_CONFIG_URI : http://config-server:9101
      EUREKA_SERVER_URL : http://localhost:8761/eureka
    networks:
      - ocpizza-network

  ocpizza-auth:
    depends_on:
      - config-server
      - eureka-server
      - database
    image: ocpizza-auth
    container_name: ocpizza-auth
    restart : always
    build:
      context: ./ocpizza-auth
      dockerfile: Dockerfile
    ports:
      - "9191:9191"
    expose:
      - "9191"
    environment:
      SPRING_CONFIG_URI: http://config-server:9101
      EUREKA_SERVER_URL : http://eureka-server:8761/eureka
      SPRING_DATASOURCE_URI : jdbc:mysql://db:3306/dbauth?createDatabaseIfNotExist=true
    networks:
      - ocpizza-network

  ocpizza-commande:
    depends_on:
      - config-server
      - eureka-server
      - database
      - ocpizza-auth
    image: ocpizza-commande
    container_name: ocpizza-commande
    restart : always
    build:
      context: ./ocpizza-commande
      dockerfile: Dockerfile
    ports:
      - "9001:9001"
    expose:
      - "9001"
    environment:
      SPRING_CONFIG_URI: http://config-server:9101
      EUREKA_SERVER_URL : http://eureka-server:8761/eureka/
      SPRING_DATASOURCE_URI: jdbc:mysql://db:3306/dbbook?createDatabaseIfNotExist=true
    networks:
      - ocpizza-network

  ocpizza-admin:
    depends_on:
      - config-server
      - eureka-server
      - database
      - ocpizza-auth
    image: ocpizza-admin
    container_name: ocpizza-admin
    restart : always
    build:
      context: ./ocpizza-admin
      dockerfile: Dockerfile
    ports:
      - "9002:9002"
    expose:
      - "9002"
    environment:
      SPRING_CONFIG_URI: http://config-server:9101
      EUREKA_SERVER_URL : http://eureka-server:8761/eureka/
      SPRING_DATASOURCE_URI: jdbc:mysql://db:3306/dbloan?createDatabaseIfNotExist=true
    networks:
      - ocpizza-network

  zuul-server:
    depends_on:
      - config-server
      - eureka-server
      - ocpizza-auth
      - ocpizza-commande
      - ocpizza-admin
    image: zuul-server
    container_name: zuul-server
    build:
      context: ./zuul-server
      dockerfile: Dockerfile
    ports:
      - "9004:9004"
    expose:
      - "9004"
    environment:
      SPRING_CONFIG_URI: http://config-server:9101
      EUREKA_SERVER_URL : http://eureka-server:8761/eureka/
    networks:
      - ocpizza-network

  client-ui:
    depends_on:
      - config-server
      - eureka-server
      - ocpizza-auth
    image: client-ui
    container_name: client-ui
    build:
      context: ./client-ui
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    expose:
      - "8000"
    environment:
      SPRING_CONFIG_URI: http://config-server:9101
      EUREKA_SERVER_URL: http://eureka-server:8761/eureka/
    networks:
      - ocpizza-network

  collaborateur-ui:
    depends_on:
      - config-server
      - eureka-server
      - ocpizza-auth
    image: collaborateur-ui
    container_name: collaborateur-ui
    build:
      context: ./collaborateur-ui
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    expose:
      - "8001"
    environment:
      SPRING_CONFIG_URI: http://config-server:9101
      EUREKA_SERVER_URL: http://eureka-server:8761/eureka/
    networks:
      - ocpizza-network

volumes :
  db_data:

networks:
  ocpizza-network:

